
import java.awt.Graphics;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Home
 */
public class frame3 extends javax.swing.JFrame {
Connection con;
  PreparedStatement ps=null;
    /**
     * Creates new form frame3
     */
   SimpleDateFormat format=new SimpleDateFormat("dd-MM-yyyy");
String Branch;
String region3;
String selected,selected2,selectedyear,Policygen;
Date date1;
int total,drive,own;
String selectedvehicle,CC,agentname,reg,name1,email1,ph,MODEL,CUSTOMERID,POLICYID,POLICYNO,CHASSIS,ENGINENO1;
  double totalpre=0,pa=0,od1=0,tp=0;
  String vt,g,vy,CLAIMBRANCH;
  String od;
   String Policyt;
   int vehicle;
    String ge,geographical;
    String colored,seating,fuel;
    public frame3() {
        initComponents();
        
    }
    public frame3(String B) throws ClassNotFoundException
    {initComponents();
    Branch=B;
    discountncbpercentage.setVisible(false);
    discountncb.setVisible(false);
    discountncbfield.setVisible(false);
           driver.setVisible(false);
         owner.setVisible(false);
    gst.setEditable(false);
    drive=0;
    own=0;
    total=0;
    print.setEnabled(false);
            idvfield3.setEditable(false);
        try { 
            Class.forName("oracle.jdbc.driver.OracleDriver");
        // TODO add your handling code here:
        con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Hari21032001");
            System.out.print(con);
            Statement stm=con.createStatement();
            Statement stm1=con.createStatement();
            
              ResultSet rs=stm.executeQuery("Select DISTINCT VEHICLETYPE_REFER from Vehicle_REFERENCE order by VEHICLETYPE_REFER ASC");
              while(rs.next())
              {
              vehicletype.addItem(rs.getString("VEHICLETYPE_REFER"));
              }
              
              
               rs=stm.executeQuery("Select * from Employee where BRANCH_NAME='"+B+"' and DESIGNATION!='"+"MANAGER"+"'");
                 while(rs.next()){
                     agent.addItem(rs.getString(2)+"("+rs.getString(1)+")");
                 }
                 rs=stm1.executeQuery("Select * from Agent where AGENT_BRANCH_REF='"+B+"'");
                 while(rs.next()){
                     agent.addItem(rs.getString(1)+"(AGENT)"+"("+rs.getString(3)+")");
                 }
                  rs=stm1.executeQuery("Select DISTINCT POLICY_TYPE from policydetails order by POLICY_TYPE desc");
                 while(rs.next()){
                     if(!"".equals(rs.getString("POLICY_TYPE"))){
                     jComboBox6.addItem(rs.getString("POLICY_TYPE"));
                     }
                 }
               
                 rs=stm1.executeQuery("Select DISTINCT GEOGRAPHICAL1  from IRDA_DETAILS order by GEOGRAPHICAL1 ASC");
                 while(rs.next()){
                     jComboBox3.addItem(rs.getString("GEOGRAPHICAL1"));
                 }
                 
               rs=stm1.executeQuery("Select * from Branch");
                 while(rs.next()){
                    claimbranchcombo.addItem(rs.getString("BRANCH_NAME1")+""+rs.getString("TYPE_BRANCH"));
                 }
con.close();
                 
    } catch (SQLException ex) {
        Logger.getLogger(frame4.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CHASSISFIELD = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        register = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cc = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        color = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        vehicletype = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        ENGINE = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        claimbranch = new javax.swing.JTextField();
        agent = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        claimbranchcombo = new javax.swing.JComboBox<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        idvfield1 = new javax.swing.JTextField();
        depreciation2 = new javax.swing.JLabel();
        gst = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ncbcheck = new javax.swing.JCheckBox();
        discountncb = new javax.swing.JLabel();
        discountncbfield = new javax.swing.JTextField();
        discountncbpercentage = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        idvfield3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        vehicleyear = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        totalprem = new javax.swing.JTextField();
        ncbcheck1 = new javax.swing.JCheckBox();
        idv1 = new javax.swing.JLabel();
        driver = new javax.swing.JCheckBox();
        owner = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        policytype = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 8, true));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("2.MAKER");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel3.setText("4.COLOR");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("5.CHASSISNO");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("6.FUEL TYPE");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel6.setText("7.GEOGRAPHICAL");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel7.setText("8.SEATING CAPACITY");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("VEHICLE DETAILS");

        CHASSISFIELD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CHASSISFIELDFocusLost(evt);
            }
        });
        CHASSISFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHASSISFIELDActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Fuel--", "Petrol", "Diesel", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Seating Capacity--", "2", "5", "8", " ", " " }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel17.setText("9.REGISTRATION NO");

        register.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerFocusLost(evt);
            }
        });
        register.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                registerKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel18.setText("10.CC/GVM");

        cc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel22.setText("3.MODEL");

        jComboBox8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox8ItemStateChanged(evt);
            }
        });
        jComboBox8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox8FocusLost(evt);
            }
        });
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jComboBox9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox9ItemStateChanged(evt);
            }
        });
        jComboBox9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox9FocusLost(evt);
            }
        });
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });

        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel20.setText("1.VEHICLE TYPE");

        vehicletype.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                vehicletypeFocusLost(evt);
            }
        });
        vehicletype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicletypeActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel25.setText("11.ENGINENO");

        ENGINE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ENGINEFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(62, 62, 62)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(vehicletype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(color, 0, 169, Short.MAX_VALUE)
                        .addComponent(jComboBox9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(CHASSISFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(register)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox4, 0, 201, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ENGINE))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vehicletype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CHASSISFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(ENGINE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel9.setText("1.NAME");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel10.setText("2.EMAIL-ID");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel11.setText("3.PHONENO");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel12.setText("4.ADDRESS");

        jLabel16.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CUSTOMER DETAILS");

        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });

        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneKeyTyped(evt);
            }
        });

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(113, 113, 113)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addContainerGap(228, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name))
                        .addGap(65, 65, 65))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addGap(14, 14, 14)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(88, 88, 88))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel13.setText("1.AGENT/INSURER NAME");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel14.setText("3.DATE OF MANUFACTURE OF VEHICLE");

        claimbranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claimbranchActionPerformed(evt);
            }
        });

        agent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel15.setText("2.CLAIM BRANCH");

        jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField10FocusLost(evt);
            }
        });
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel27.setText("FORMAT(DD-MM-YYYY)");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(claimbranchcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(claimbranch, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(agent, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(claimbranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claimbranchcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("POLICY PAGE");

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 7, true));

        idvfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idvfield1ActionPerformed(evt);
            }
        });

        depreciation2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        depreciation2.setText("GST");

        gst.setText("18");

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("%");

        ncbcheck.setText("NCB(NO BONUS CERTIFICATE)");
        ncbcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ncbcheckActionPerformed(evt);
            }
        });

        discountncb.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        discountncb.setText("DISCOUNT FOR NCB");

        discountncbpercentage.setBackground(new java.awt.Color(0, 0, 0));
        discountncbpercentage.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        discountncbpercentage.setForeground(new java.awt.Color(255, 255, 255));
        discountncbpercentage.setText("%");

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel24.setText("THIRD PARTY AMOUNT");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("AGE OF VEHICLE");

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel19.setText("TOTAL PREMIUM");

        ncbcheck1.setText("PERSONAL ACCIDENT COVERAGE");
        ncbcheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ncbcheck1ActionPerformed(evt);
            }
        });

        idv1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        idv1.setText("IDV(INSURED DECLARED VALUE)");

        driver.setText("FOR DRIVER");
        driver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverActionPerformed(evt);
            }
        });

        owner.setText("FOR OWNER");
        owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerActionPerformed(evt);
            }
        });

        jButton2.setText("CALCULATE");
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton2FocusLost(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        print.setText("GENERATE POLICY");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel26.setText("RS");

        policytype.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        policytype.setText("POLICY TYPE");

        jComboBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox6ItemStateChanged(evt);
            }
        });
        jComboBox6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox6FocusLost(evt);
            }
        });
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(depreciation2)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(idv1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel24)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(vehicleyear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(idvfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(idvfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jComboBox6, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(ncbcheck)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(discountncb)
                                        .addGap(32, 32, 32)
                                        .addComponent(discountncbfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(discountncbpercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(286, 286, 286)
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(gst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(driver)))
                                            .addComponent(ncbcheck1))
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(227, 227, 227)))
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalprem, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(policytype, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(policytype, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vehicleyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(idvfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idvfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idv1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(depreciation2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ncbcheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(discountncb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountncbfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountncbpercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ncbcheck1)
                            .addComponent(driver)
                            .addComponent(owner))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalprem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(jLabel21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1090, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void ccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccActionPerformed

    private void claimbranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claimbranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claimbranchActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void vehicletypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicletypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicletypeActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox8FocusLost
         
        
    }//GEN-LAST:event_jComboBox8FocusLost

    private void jComboBox8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox8ItemStateChanged
        // TODO add your handling code here:
        selected=jComboBox8.getItemAt(jComboBox8.getSelectedIndex());
        System.out.print(selected);
        jComboBox9.removeAllItems();
 
        try {
                   con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Hari21032001");
        // TODO add your handling code here
            Statement stm=con.createStatement();
               ResultSet rs=stm.executeQuery("Select DISTINCT MODEL from Vehicle_REFERENCE where MAKER='"+selected+"' order by MODEL");
              while(rs.next())
              {
                
              
                  jComboBox9.addItem(rs.getString("MODEL"));
              
              }
              con.close();
             
    } catch (SQLException ex) {
        Logger.getLogger(frame4.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jComboBox8ItemStateChanged

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed

    private void agentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agentActionPerformed

    private void vehicletypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vehicletypeFocusLost
    vehicleyear.removeAllItems();
        cc.removeAllItems();
       jComboBox8.removeAllItems();
         selectedvehicle=vehicletype.getItemAt(vehicletype.getSelectedIndex());
      try {
                 con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Hari21032001");
        // TODO add your handling code here
            Statement stm=con.createStatement();
             ResultSet rs=stm.executeQuery("Select DISTINCT MAKER from Vehicle_REFERENCE where VEHICLETYPE_REFER='"+selectedvehicle+"'order by MAKER ASC");
              while(rs.next())
              {
                  jComboBox8.addItem(rs.getString("MAKER"));
              }
              rs=stm.executeQuery("Select DISTINCT CC from IRDA_VEHICLE_REFERENCE where VEHICLETYPE='"+selectedvehicle+"' order by CC");
              while(rs.next())
              {
                
                  cc.addItem(rs.getString("CC"));
              
              }
             rs=stm.executeQuery("Select DISTINCT YEAR from IRDA_VEHICLE_REFERENCE  where VEHICLETYPE='"+selectedvehicle+"' order by YEAR");
              while(rs.next())
              {
                  if(!"NULL".equals(rs.getString("YEAR"))){
                  vehicleyear.addItem(rs.getString("YEAR"));
                  }
              }
             con.close();
             
    } catch (SQLException ex) {
        Logger.getLogger(frame4.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_vehicletypeFocusLost

    private void jComboBox9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox9FocusLost
       
    }//GEN-LAST:event_jComboBox9FocusLost

    private void jComboBox9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox9ItemStateChanged
        // TODO add your handling code here:
        color.removeAllItems();
          selected2=jComboBox9.getItemAt(jComboBox9.getSelectedIndex());
        System.out.print(selected2);
        try {
                   con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Hari21032001");
        // TODO add your handling code here
            Statement stm=con.createStatement();
              ResultSet rs=stm.executeQuery("Select DISTINCT COLOR from Vehicle_REFERENCE where MODEL='"+selected2+"' order by COLOR");
              while(rs.next())
              {
                
                  color.addItem(rs.getString("COLOR"));
              
              }
              con.close();
             
             
    } catch (SQLException ex) {
        Logger.getLogger(frame4.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jComboBox9ItemStateChanged

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        CHASSIS=CHASSISFIELD.getText();
        ENGINENO1=ENGINE.getText();
      //  CLAIMBRANCH=claimbranch.getText();
        CLAIMBRANCH=claimbranchcombo.getItemAt(claimbranchcombo.getSelectedIndex());
        String sql="insert into Customer(CUST_NAME,CUST_PHONENO,CUST_EMAIL,BRANCH_PURCHASED,CUST_ID)values(?,?,?,?,?)";
    try {
               con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Hari21032001");
        ps=con.prepareStatement(sql);
        ps.setString(1,name1);
                ps.setString(2,ph);
                ps.setString(3,email1);
                ps.setString(4,Branch);
                ps.setString(5,"");
                ps.executeUpdate();
                
          Statement stm=con.createStatement();
           ResultSet rs1=stm.executeQuery("Select * from Customer");
           while(rs1.next()){
                CUSTOMERID=rs1.getString("CUST_ID");
           }
              ResultSet rs=stm.executeQuery("Select MODELID from Vehicle_REFERENCE where MAKER='"+selected+"' AND MODEL='"+selected2+"' AND COLOR='"+colored+"'");
              while(rs.next())
              {
                   MODEL=rs.getString("MODELID");
              }      
                 
            SimpleDateFormat formatter=new SimpleDateFormat("dd-MM-yyyy");
              Date today=new Date();
              Calendar now=Calendar.getInstance();
              int year=Calendar.getInstance().get(Calendar.YEAR);
              String year2=String.valueOf(year);
            POLICYNO=Branch+year2;
            rs=stm.executeQuery("Select policynogenerator from policygenerater");
              while(rs.next())
              {
                   Policygen=rs.getString("policynogenerator");
              }      
            POLICYNO+=Policygen;
            if("THIRD-PARTY INSURANCE".equals(jComboBox6.getItemAt(jComboBox6.getSelectedIndex()))){
                   Policyt="THIRD-PARTY INSURANCE";   
                   }
                   else if("THIRD-PARTY INSURANCE".equals(jComboBox6.getItemAt(jComboBox6.getSelectedIndex())) && driver.isSelected() && owner.isSelected()){
                  Policyt="THIRD-PARTY INSURANCE"+","+"PERSONAL ACCIDENT FOR DRIVER"+","+"OWNER";
                  }
                  else if("THIRD-PARTY INSURANCE".equals(jComboBox6.getItemAt(jComboBox6.getSelectedIndex())) && owner.isSelected()){
                  Policyt="THIRD-PARTY INSURANCE"+","+"PERSONAL ACCIDENT FOR OWNER";
                  }
                  else if("THIRD-PARTY INSURANCE".equals(jComboBox6.getItemAt(jComboBox6.getSelectedIndex())) && driver.isSelected()){
                  Policyt="THIRD-PARTY INSURANCE"+","+"PERSONAL ACCIDENT FOR DRIVER";
                  }
                  else if("OWN DAMAGE COVER".equals(jComboBox6.getItemAt(jComboBox6.getSelectedIndex()))){
                  Policyt="OWN DAMAGE COVER";    
                  }
                    else if("OWN DAMAGE COVER".equals(jComboBox6.getItemAt(jComboBox6.getSelectedIndex())) && driver.isSelected() && owner.isSelected()){
                  Policyt="OWN DAMAGE COVER"+","+"PERSONAL ACCIDENT FOR DRIVER"+","+"OWNER";
                  }
                  else if("OWN DAMAGE COVER".equals(jComboBox6.getItemAt(jComboBox6.getSelectedIndex())) && owner.isSelected()){
                  Policyt="OWN DAMAGE COVER"+","+"PERSONAL ACCIDENT FOR OWNER";
                  }
                  else if("OWN DAMAGE COVER".equals(jComboBox6.getItemAt(jComboBox6.getSelectedIndex())) && driver.isSelected()){
                  Policyt="OWN DAMAGE COVER"+","+"PERSONAL ACCIDENT FOR DRIVER";
                  }
             sql="insert into Vehicle(MODELID1,CHASISSNO,ENGINENO,CUST_ID_REFER,REGISTRATION_NUMBER,MAN_YEAR,POLCYNO,INSURERNAME,POLICY_PURCHASED,POLICY_TYPE,AMOUNT) values(?,?,?,?,?,?,?,?,?,?,?)";
                 ps=con.prepareStatement(sql);
                 ps.setString(1,MODEL);
                ps.setString(2,CHASSIS);
                ps.setString(3,ENGINENO1);
                ps.setString(4,CUSTOMERID);
                ps.setString(5,reg);
                ps.setString(6,String.valueOf(date1));
                ps.setString(7,POLICYNO);
                ps.setString(8,agent.getItemAt(agent.getSelectedIndex()));
                  ps.setString(9,formatter.format(today));
                   ps.setString(10,Policyt);
                   ps.setString(11,totalprem.getText());
                ps.executeUpdate();
                
                con.close();
                 frame5 f5=new frame5(this);
         f5.setVisible(true);
        this.setEnabled(false);
        this.setVisible(false); 
    } 
    catch (SQLException ex) {
        Logger.getLogger(frame3.class.getName()).log(Level.SEVERE, null, ex);
    }
                  
          
        
    }//GEN-LAST:event_printActionPerformed

    private void idvfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idvfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idvfield1ActionPerformed

    private void ncbcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ncbcheckActionPerformed
        // TODO add your handling code here:
       if(ncbcheck.isSelected()){
           discountncbpercentage.setVisible(true);
    discountncb.setVisible(true);
    discountncbfield.setVisible(true);
       }
       else{
           discountncbpercentage.setVisible(false);
    discountncb.setVisible(false);
    discountncbfield.setVisible(false);
       }
    }//GEN-LAST:event_ncbcheckActionPerformed

    private void jComboBox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox6ItemStateChanged
        // TODO add your handling code here:
        
        try {
        if("THIRD-PARTY INSURANCE".equals(jComboBox6.getItemAt(jComboBox6.getSelectedIndex()))){
            jLabel2.setVisible(false);
            vehicleyear.setVisible(false);
            idv1.setVisible(false);
            idvfield1.setVisible(false);
             CC=cc.getItemAt(cc.getSelectedIndex());
             con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Hari21032001");
            Statement stm=con.createStatement();
              ResultSet rs=stm.executeQuery("Select VEHICLEID from IRDA_VEHICLE_REFERENCE where CC='"+CC+"' AND YEAR='"+"NULL"+"'");
              while(rs.next())
              {
                vehicle=rs.getInt("VEHICLEID");

              }      
              
              rs=stm.executeQuery("Select * from IRDA_DETAILS where VEHICLEID1='"+vehicle+"' ");
              while(rs.next())
              { POLICYNO=rs.getString(1);
                idvfield3.setText(rs.getString("AMOUNT"));
              }      con.close();}
        else {
           jLabel2.setVisible(true);
            vehicleyear.setVisible(true);
            idv1.setVisible(true);
            idvfield1.setVisible(true);
            CC=cc.getItemAt(cc.getSelectedIndex());
            con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Hari21032001");
            Statement stm=con.createStatement();
              ResultSet rs=stm.executeQuery("Select VEHICLEID from IRDA_VEHICLE_REFERENCE where CC='"+CC+"' AND YEAR='"+"NULL"+"'");
              while(rs.next())
              {
                vehicle=rs.getInt("VEHICLEID");

              }      
              
              rs=stm.executeQuery("Select AMOUNT from IRDA_DETAILS where VEHICLEID1='"+vehicle+"' ");
              while(rs.next())
              {
                idvfield3.setText(rs.getString("AMOUNT"));
              } 
              
           con.close();
        }
             
    } catch (SQLException ex) {
        Logger.getLogger(frame4.class.getName()).log(Level.SEVERE, null, ex);
    } 
    }//GEN-LAST:event_jComboBox6ItemStateChanged

    private void jComboBox6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox6FocusLost
       
        try {
        // TODO add your handling code here
        if("THIRD-PARTY INSURANCE".equals(jComboBox6.getItemAt(jComboBox6.getSelectedIndex()))){
                   con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Hari21032001");
             CC=cc.getItemAt(cc.getSelectedIndex());
            Statement stm=con.createStatement();
              ResultSet rs=stm.executeQuery("Select VEHICLEID from IRDA_VEHICLE_REFERENCE where CC='"+CC+"' AND YEAR='"+"NULL"+"'");
              while(rs.next())
              {
                vehicle=rs.getInt("VEHICLEID");
                 System.out.print(vehicle);
              }      
              
              rs=stm.executeQuery("Select * from IRDA_DETAILS where VEHICLEID1='"+vehicle+"' ");
              while(rs.next())
              { 
                idvfield3.setText(rs.getString(6));
                System.out.println(rs.getString(6));
              }      
        }       con.close();
             
    } catch (SQLException ex) {
        Logger.getLogger(frame4.class.getName()).log(Level.SEVERE, null, ex);
    } 
    }//GEN-LAST:event_jComboBox6FocusLost

    private void ncbcheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ncbcheck1ActionPerformed
         if(ncbcheck1.isSelected()){
    driver.setVisible(true);
    owner.setVisible(true);
    totalprem.setText(String.valueOf(totalpre));
       }
       else{
        
           driver.setVisible(false);
         owner.setVisible(false);
         driver.setSelected(false);
         owner.setSelected(false);
         drive=0;
    own=0;
   
     
         }
    }//GEN-LAST:event_ncbcheck1ActionPerformed

    private void driverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverActionPerformed
        
    }//GEN-LAST:event_driverActionPerformed

    private void ownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerActionPerformed
        
    }//GEN-LAST:event_ownerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if("".equals(idvfield3.getText())){
              JOptionPane.showMessageDialog(null,"PLEASE SELECT POLICYTYPE");
        }
        else{
        print.setEnabled(true);
        pa=0;
        if(ncbcheck1.isSelected()){
           pa=0;
           if(driver.isSelected())
           {
               pa+=50;
           }
           else{
            JOptionPane.showMessageDialog(null,"PLEASE SELECT PA OR UNCHECK THE PACHECKBOX");
            ncbcheck1.setSelected(false);
           }
           if(owner.isSelected())
           {
               pa+=275;
           }
          
       }
        else{
            owner.setVisible(false);
            driver.setVisible(false);
        }
        try{
                   con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Hari21032001");
        if("THIRD-PARTY INSURANCE".equals(jComboBox6.getItemAt(jComboBox6.getSelectedIndex()))){
          tp=Integer.parseInt(idvfield3.getText());
        
            int g=Integer.parseInt(gst.getText());
            if(ncbcheck.isSelected()){
                if(!"".equals(discountncbfield.getText())){
                int ncb=Integer.parseInt(discountncbfield.getText());
                totalpre=tp*(0.18);
                System.out.println(totalpre);
                totalpre-=tp*ncb/100;
                 System.out.println(totalpre);
                totalpre+=tp;
                tp=totalpre;
                totalpre+=pa;
                System.out.print(totalpre);
                totalprem.setText(String.valueOf(totalpre));
                }
                else{
                    JOptionPane.showMessageDialog(null,"PLEASE ENETER THE VALUE FOR NCB FIELD");
                }
            }
            else{
                System.out.println(g);
                 totalpre=(tp*g/100)+tp;
                 totalpre+=pa;
                totalprem.setText(String.valueOf(totalpre));
            }
             vt=vehicletype.getItemAt(vehicletype.getSelectedIndex());
             geographical=jComboBox3.getItemAt(jComboBox3.getSelectedIndex());
             vy=vehicleyear.getItemAt(vehicleyear.getSelectedIndex());
             fuel=jComboBox2.getItemAt(jComboBox2.getSelectedIndex());
            colored=color.getItemAt(color.getSelectedIndex());
            seating=jComboBox4.getItemAt(jComboBox4.getSelectedIndex());
            agentname=agent.getItemAt(agent.getSelectedIndex());
            reg=register.getText();
            name1=name.getText();
            email1=email.getText();
            ph=phone.getText();
      }
        else{
             tp=Integer.parseInt(idvfield3.getText());
        
            int gee=Integer.parseInt(gst.getText());
            if(ncbcheck.isSelected()){
                if(!"".equals(discountncbfield.getText())){
                int ncb=Integer.parseInt(discountncbfield.getText());
                totalpre=tp*gee/100;
                System.out.println(totalpre);
                totalpre-=tp*ncb/100;
                 System.out.println(totalpre);
                totalpre+=tp;
                tp=totalpre;
                totalpre+=pa;
                System.out.print(totalpre);
                }
                else{
                    JOptionPane.showMessageDialog(null,"PLEASE ENETER THE VALUE FOR NCB FIELD");
                }
            }
            else{
                System.out.println(gee);
                 totalpre=(tp*gee/100)+tp;
                 totalpre+=pa;
            }
            
            CC=cc.getItemAt(cc.getSelectedIndex());
             vt=vehicletype.getItemAt(vehicletype.getSelectedIndex());
             geographical=jComboBox3.getItemAt(jComboBox3.getSelectedIndex());
            vy=vehicleyear.getItemAt(vehicleyear.getSelectedIndex());
            Statement stm=con.createStatement();
              ResultSet rs=stm.executeQuery("Select VEHICLEID from IRDA_VEHICLE_REFERENCE where CC='"+CC+"' AND YEAR='"+vy+"' AND VEHICLETYPE='"+vt+"'");
              while(rs.next())
              {System.out.println("VEHICLEID"+rs.getString("VEHICLEID"));
                ge=rs.getString("VEHICLEID");
              }      
             rs=stm.executeQuery("Select * from IRDA_DETAILS where VEHICLEID1='"+ge+"' AND GEOGRAPHICAL1='"+geographical+"'");
              while(rs.next())
              { 
                od=rs.getString(6);
                POLICYNO=rs.getString(1);
                System.out.println(rs.getString(1));
              }
            if(!"".equals(idvfield1.getText())){
            int idv=Integer.parseInt(idvfield1.getText());
            od1=(idv*Double.parseDouble(od))/100;
            double tot=od1+totalpre;
            System.out.print(tot);
            totalprem.setText(String.valueOf(tot));
        }
            else{
                JOptionPane.showMessageDialog(null,"PLEASE ENTER VALUE IN IDVFIELD");
            }
            fuel=jComboBox2.getItemAt(jComboBox2.getSelectedIndex());
            colored=color.getItemAt(color.getSelectedIndex());
            seating=jComboBox4.getItemAt(jComboBox4.getSelectedIndex());
      agentname=agent.getItemAt(agent.getSelectedIndex());
       reg=register.getText();
            name1=name.getText();
            email1=email.getText();
            ph=phone.getText();
        }
          
               
                con.close();
       
      }
      catch(NumberFormatException e)
      {
           JOptionPane.showMessageDialog(null,"PLEASE ENTER INTEGER VALUE");
      } catch (SQLException ex) {
        Logger.getLogger(frame3.class.getName()).log(Level.SEVERE, null, ex);
    }}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusLost
      String date=jTextField10.getText();
     
    try {
        Date today=new Date();
        date1=format.parse(date);
        SimpleDateFormat format1=new SimpleDateFormat("dd-MM-yyyy");
      
        if(date1.after(today)){
             JOptionPane.showMessageDialog(null,"THE GIVEN DATE IS GRETAER THAN THE CURRENT DATE");
             jTextField10.setText("");
        }
        
    } catch (ParseException ex) {
    JOptionPane.showMessageDialog(null,"DATE FORMAT IS WRONG PLEASE ENTER THE CORRECT FORMAT");
    }
    }//GEN-LAST:event_jTextField10FocusLost

    private void CHASSISFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHASSISFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHASSISFIELDActionPerformed

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost

             if(name.getText().isEmpty())
             {
                  //JOptionPane.showMessageDialog(null,"NAME FIELD SHOULD NOT BE EMPTY");
             }
           
    }//GEN-LAST:event_nameFocusLost

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
    try {
        con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Hari21032001");
    } catch (SQLException ex) {
        Logger.getLogger(frame3.class.getName()).log(Level.SEVERE, null, ex);
    }
        Statement stm;
    //try {
        /*stm = con.createStatement();
         ResultSet rs=stm.executeQuery("Select CUST_EMAIL  from Customer where CUST_EMAIL ='"+email.getText()+"'");
              while(rs.next())
              {
               if(rs.getString("CUST_EMAIL ").equals(email.getText()))
               {
                   JOptionPane.showMessageDialog(null,"EMAIL ALREADY EXIST");
               }
              }
              con.close();
    }
    catch (SQLException ex) {
        Logger.getLogger(frame3.class.getName()).log(Level.SEVERE, null, ex);
    }
             */
       
    }//GEN-LAST:event_emailFocusLost

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost
     //try {
        if("".equals(phone.getText()))
        {
            JOptionPane.showMessageDialog(null,"PHONENOFIELD SHOULD NOT BE EMPTY");
        }
        else if(!"".equals(phone.getText())){
        /*con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Hari21032001");
        Statement stm=con.createStatement();
              ResultSet rs=stm.executeQuery("Select CUST_PHONENO from Customer where CUST_PHONENO='"+phone.getText()+"'");
              while(rs.next())
              {
               if(rs.getString("CUST_PHONENO").equals(phone.getText()))
               {
                   JOptionPane.showMessageDialog(null,"PHONE NUMBER ALREADY EXIST");
               }
              }
              con.close();
    }} catch (SQLException ex) {
        Logger.getLogger(frame3.class.getName()).log(Level.SEVERE, null, ex);
    }   */}
    }//GEN-LAST:event_phoneFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        jLabel29.setText("");
    }//GEN-LAST:event_emailFocusGained

    private void registerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerFocusLost
    try {
        if("".equals(register.getText()))
        {
            JOptionPane.showMessageDialog(null,"REGISTRATION NUMBER FIELD SHOULD NOT BE EMPTY");
            register.requestFocus();
        }
        else if(!"".equals(register.getText())){
        con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Hari21032001");
        Statement stm=con.createStatement();
              ResultSet rs=stm.executeQuery("Select REGISTRATION_NUMBER from Vehicle where REGISTRATION_NUMBER='"+register.getText()+"'");
              while(rs.next())
              {
               if(rs.getString("REGISTRATION_NUMBER").equals(register.getText()))
               {
                   JOptionPane.showMessageDialog(null,"REGISTRATION NUMBER ALREADY EXIST");
               }
              }
              con.close();
    }} catch (SQLException ex) {
        Logger.getLogger(frame3.class.getName()).log(Level.SEVERE, null, ex);
    }
         
            
    }//GEN-LAST:event_registerFocusLost

    private void CHASSISFIELDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CHASSISFIELDFocusLost
        try {
        if("".equals(CHASSISFIELD.getText()))
        {
            JOptionPane.showMessageDialog(null,"CHASISSNO NUMBER FIELD SHOUL NOT BE EMPTY");
            CHASSISFIELD.requestFocus();
        }
        else if(!"".equals(CHASSISFIELD.getText())){
        con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Hari21032001");
        Statement stm=con.createStatement();
              ResultSet rs=stm.executeQuery("Select CHASISSNO from Vehicle where CHASISSNO='"+CHASSISFIELD.getText()+"'");
              while(rs.next())
              {
               if(rs.getString("CHASISSNO").equals(CHASSISFIELD.getText()))
               {
                   JOptionPane.showMessageDialog(null,"CHASISSNO NUMBER ALREADY EXIST");
                   CHASSISFIELD.setText("");
               }
              }
              con.close();
    }} catch (SQLException ex) {
        Logger.getLogger(frame3.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_CHASSISFIELDFocusLost

    private void ENGINEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ENGINEFocusLost
        try {
        if("".equals(ENGINE.getText()))
        {
            JOptionPane.showMessageDialog(null,"ENGINE NUMBER FIELD SHOUL NOT BE EMPTY");
            ENGINE.requestFocus();
        }
        else if(!"".equals(ENGINE.getText())){
        con =DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Hari21032001");
        Statement stm=con.createStatement();
              ResultSet rs=stm.executeQuery("Select ENGINENO from Vehicle where ENGINENO='"+ENGINE.getText()+"'");
              while(rs.next())
              {
               if(rs.getString("ENGINENO").equals(ENGINE.getText()))
               {
                   JOptionPane.showMessageDialog(null,"ENGINE NUMBER ALREADY EXIST");
                   ENGINE.setText("");
               }
              }
              con.close();
    }} catch (SQLException ex) {
        Logger.getLogger(frame3.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_ENGINEFocusLost

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
      
    }//GEN-LAST:event_nameKeyPressed

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
       if(!"".equals(name.getText())){
                 if(name.getText().matches("^[a-zA-Z\\s]{1,}[\\.]{0,1}[A-Za-z\\s]{0,}$")){
                 jLabel28.setText("");
             }
                 else{
                     jLabel28.setText("INVALID NAME!!");
                 }
      }
    }//GEN-LAST:event_nameKeyTyped

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
        String emailregex="^[a-zA-Z0-9_+&*-]+(?:\\."+
                         "[a-zA-Z0-9_+&*-]+)*@"+
                          "(?:[a-zA-Z0-9-]+\\.)+[a-z"+"A-Z]{2,7}$";
       Pattern pat=Pattern.compile(emailregex);
       if(!pat.matcher(email.getText()).matches())
       {
             jLabel29.setText("EMAIL IS NOT A VALD ONE");
             email.setFocusable(true);
       }
       else{
           jLabel29.setText("");
       }
    }//GEN-LAST:event_emailKeyTyped

    private void phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyTyped
     String phoneno=phone.getText();
        if(phoneno.matches("[0-9]+")&& phoneno.length()==9)
        {jLabel30.setText("");
            address.requestFocus();
        }
        else{
             jLabel30.setText("PHONENO IS NOT A VALD ONE");
        }
    }//GEN-LAST:event_phoneKeyTyped

    private void registerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerKeyTyped
        String emailregex="^[A-Z]{2}\\s[0-9]{2}\\s[A-Z]{2}\\s[0-9]{3}$";
       Pattern pat=Pattern.compile(emailregex);
       if(!pat.matcher(register.getText()).matches())
       {
             jLabel31.setText("REGISTRATIONNO IS NOT A VALID!");
             register.setFocusable(true);
       }
       else{
           jLabel31.setText("");
       }
    }//GEN-LAST:event_registerKeyTyped

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFocusGained

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFocusGained

    private void jFormattedTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField1FocusLost
         String date=jFormattedTextField1.getText();
     
    try {
        Date today=new Date();
        date1=format.parse(date);
        SimpleDateFormat format1=new SimpleDateFormat("dd-MM-yyyy");
      
        if(date1.after(today)){
             JOptionPane.showMessageDialog(null,"THE GIVEN DATE IS GRETAER THAN THE CURRENT DATE");
             jTextField10.setText("");
        }
        
    } catch (ParseException ex) {
    JOptionPane.showMessageDialog(null,"DATE FORMAT IS WRONG PLEASE ENTER THE CORRECT FORMAT");
    }
    }//GEN-LAST:event_jFormattedTextField1FocusLost

    private void jButton2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusLost
      // print.setEnabled(false);
    }//GEN-LAST:event_jButton2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CHASSISFIELD;
    private javax.swing.JTextField ENGINE;
    private javax.swing.JTextArea address;
    private javax.swing.JComboBox<String> agent;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cc;
    private javax.swing.JTextField claimbranch;
    private javax.swing.JComboBox<String> claimbranchcombo;
    private javax.swing.JComboBox<String> color;
    private javax.swing.JLabel depreciation2;
    private javax.swing.JLabel discountncb;
    private javax.swing.JTextField discountncbfield;
    private javax.swing.JLabel discountncbpercentage;
    private javax.swing.JCheckBox driver;
    private javax.swing.JTextField email;
    private javax.swing.JTextField gst;
    private javax.swing.JLabel idv1;
    private javax.swing.JTextField idvfield1;
    private javax.swing.JTextField idvfield3;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField10;
    public javax.swing.JTextField name;
    private javax.swing.JCheckBox ncbcheck;
    private javax.swing.JCheckBox ncbcheck1;
    private javax.swing.JCheckBox owner;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel policytype;
    private javax.swing.JButton print;
    private javax.swing.JTextField register;
    private javax.swing.JTextField totalprem;
    private javax.swing.JComboBox<String> vehicletype;
    private javax.swing.JComboBox<String> vehicleyear;
    // End of variables declaration//GEN-END:variables
}
